# =========================================================
# Project: Terraform Continuous Integration (CI)
# Author: Mohammed Irshad 
# Description: This workflow automatically checks the 
#              Terraform code for errors on every push.
# =========================================================

name: 'Terraform CI'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform_check:
    name: 'Terraform Lint and Validate'
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from your repository
    - name: Checkout
      uses: actions/checkout@v3

    # Step 2: Install Terraform on the GitHub Runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Initialize Terraform (Checks for provider plugins)
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform-projects

    # Step 4: Check if the code is formatted correctly
    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform-projects

    # Step 5: Validate the syntax of the code
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform-projects
