# Project: Terraform Continuous Integration (CI)
# Author: Mohammed Irshad 
# Description: Automated linting and validation for Terraform code.
# =========================================================

name: 'Terraform CI'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform_check:
    name: 'Terraform Lint and Validate'
    runs-on: ubuntu-latest
    
    # Ye block batata hai ki saari commands 'terraform-project' folder mein chalani hain
    defaults:
      run:
        working-directory: ./terraform-project

    steps:
    # Step 1: Repository se code nikalna
    - name: Checkout
      uses: actions/checkout@v3

    # Step 2: GitHub Runner pe Terraform install karna
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Terraform ko initialize karna (Providers download honge)
    - name: Terraform Init
      run: terraform init

    # Step 4: Formatting check karna
    - name: Terraform Format Check
      run: terraform fmt -check

    # Step 5: Syntax aur logic validate karna
    - name: Terraform Validate
      run: terraform validate
